/* 
 * QueryBuilderApi
 *
 * Active Query Builder Web API lets create, analyze and modify SQL queries for different database servers using RESTful HTTP requests to a cloud-based service. It requires SQL execution context (information about database schema and used database server) to be stored under the registered account at https://webapi.activequerybuilder.com/.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@activedbsoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using WebApi.ActiveQueryBuilder.Client;
using WebApi.ActiveQueryBuilder.Api;
using WebApi.ActiveQueryBuilder.Model;

namespace WebApi.ActiveQueryBuilder.Test
{
    /// <summary>
    ///  Class for testing ActiveQueryBuilderApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ActiveQueryBuilderApiTests
    {
        private ActiveQueryBuilderApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ActiveQueryBuilderApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ActiveQueryBuilderApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ActiveQueryBuilderApi
            //Assert.IsInstanceOfType(typeof(ActiveQueryBuilderApi), instance, "instance is a ActiveQueryBuilderApi");
        }

        
        /// <summary>
        /// Test GetQueryColumnsPost
        /// </summary>
        [Test]
        public void GetQueryColumnsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SqlQuery query = null;
            //var response = instance.GetQueryColumnsPost(query);
            //Assert.IsInstanceOf<List<QueryColumn>> (response, "response is List<QueryColumn>");
        }
        
        /// <summary>
        /// Test TransformSQLPost
        /// </summary>
        [Test]
        public void TransformSQLPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Transform transform = null;
            //var response = instance.TransformSQLPost(transform);
            //Assert.IsInstanceOf<TransformResult> (response, "response is TransformResult");
        }
        
    }

}
